[package]
name = "mock_iusd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9"
ic-cdk = "0.11"
serde = { version = "1.0", features = ["derive"] }
